import Head from "next/head"

import ArticlesComponent from "@/widgets/articles"
import { Equipments } from "@/widgets/equipment"
import { Footer } from "@/widgets/footer"
import { Header } from "@/widgets/header"
import { Hero } from "@/widgets/hero"
import { Questions } from "@/widgets/questions"
import { QuestionsArticle } from "@/widgets/questions-article"
import { Services } from "@/widgets/services"

const HomePage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="site-container">
				<div className="header_wrapper">
					<Header />
					<Hero />
				</div>
				<div className="services-wrapper">
					<Services />
				</div>
				<div className="equipment_wrapper">
					<Equipments />
					<ArticlesComponent />
					<div className="ellipse_wrapper">
						<Questions />
						<QuestionsArticle />
					</div>
				</div>
				<Footer />
			</div>
		</>
	)
}

export default HomePage
